version: '3.1'

services: 
  mongo_db:
    build:
      context: './'
      dockerfile: './.docker/Dockerfile'
    image: mongo 
    environment: 
      MONGO_INITDB_ROOT_USERNAME: knoledge
      MONGO_INITDB_ROOT_PASSWORD: p#secret123
    volumes: 
      - mongo-db:/data/mongo
    ports: 
      - 27017:27017
volumes:
  mongo-db:
      